file_cache_path           "/tmp/chef/cache"
data_bag_path             "/tmp/chef/data_bags"
encrypted_data_bag_secret "/tmp/chef/data_bag_key"
cookbook_path             "/tmp/chef/cookbooks"
role_path                 "/tmp/chef/roles"
